#!/usr/bin/env bash
# This script is displaying username, userid and home directory using read
#Script that displays the content of the file /etc/passwd
while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
