#!/usr/bin/env bash
#Creating a script that uses a while loop
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    x=$(( x + 1 ))
done

#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

while ((c < 10))
do
	echo "Holberton School"
	(( c++ ))
done
