#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and Hi if c is 9
x=1
while [ $x -le 10 ]
do
    echo "Best School\n"
    if [ $x -eq 9 ]
    then
	echo "Hi"
    fi
    ((x++))
done
