#!/usr/bin/env bash
# This script is displaying "Holberton School" with conditionals to show other sentences.
c=1
while ((c <= 10)); do
    if((c == 4));then
	echo "bad luck"
    elif((c == 8));then
	echo "good luck"
    else
	echo "Best School";
    fi
    ((c++))
done

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
	    echo "bad luck"
	elif [ $x -eq 8 ]
	then
	    echo "good luck"
       	else
	    echo "Holberton School"
	fi
	((x++))
done
