#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
while ((hour <= 12)); do
echo "Hour: $hour"
    minutes=1
    while [ $minutes -lt 60 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hour++))
done
