#!/usr/bin/env bash
# Bash script that displats all active IPv4 IPs on executing machine
ifconfig | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1
#ifconfig lo | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1
